name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: ls #docker build . --file titanic-backend/Dockerfile --tag lukaszsedek/titanic-backend:$(date +%s)
